apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacttest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacttest
  template:
    metadata:
      labels:
        app: pacttest
    spec:
      containers:
      - name: pacttest
        image: chinnudocker555/pacttest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: pacttest-svc
spec:
  selector:
    app: pacttest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
