apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacttest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacttest
  template:
    metadata:
      labels:
        app: pacttest
    spec:
      containers:
      - name: pacttest
        image: chinnudocker555/pacttest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: pacttest-svc
spec:
  selector:
    app: pacttest
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
